### ISSUE TITLE
Members page, designate group administrator button not work

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#100]

**Comment by pavkahanov** [comment]
Now we can start voting for this, also removed posibility start this voting for ERC20 group

**Comment by PUndef** [comment]
1. 
![Screenshot_1](https://user-images.githubusercontent.com/25167303/71501791-fe9f0680-289e-11ea-97fb-dacb7bfc778b.png)
2.
![Screenshot_2](https://user-images.githubusercontent.com/25167303/71501798-0fe81300-289f-11ea-9421-bb60da6ec6ed.png)
3. Input pass
4.
![Screenshot_3](https://user-images.githubusercontent.com/25167303/71501831-4160de80-289f-11ea-98f8-581879ca7267.png)

Admin icon not changed in list
![Screenshot_4](https://user-images.githubusercontent.com/25167303/71501867-6bb29c00-289f-11ea-8c24-2b208761a91f.png)

After reopening page & reopening app the situation does not change

**Comment by PUndef** [comment]
It's correct. In voting should appear new voting with this question & only after this it's be changed

**Comment by PUndef** [comment]
For a better understanding, I think you need to do a redirect to the voting page, where this question should be in top
