### ISSUE TITLE
New questions, bug on close voting

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#121]
1. Vote for new question
2. Approve
3. Vote with new question
4. Try complete & get bug:
```
Uncaught (in promise) Error: Returned error: gas required exceeds allowance (7900000) or always failing transaction
    at Object.ErrorResponse (errors.js:29)
    at eval (index.js:140)
    at XMLHttpRequest.request.onreadystatechange (index.js:102)
```

**Comment by pavkahanov** [comment]
This throw error bacause function with methodSelector for testing (0x00000000) not exists in contract.
If we try to dublicate one of questions, this problem will be solved

**Comment by PUndef** [comment]
**app--fixed-6** branch
