### ISSUE TITLE
Create new question errors

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#122]
- [x] Create new question without function selector cause error
It's should work correctly without value
Error:
```
Uncaught (in promise) Error: invalid bytes4 value (arg="_methodSelector", coderType="bytes4", value="")
    at Object.throwError (errors.js:68)
    at CoderFixedBytes.encode (abi-coder.js:433)
    at eval (abi-coder.js:605)
    at Array.forEach (<anonymous>)
    at pack (abi-coder.js:604)
    at CoderTuple.encode (abi-coder.js:764)
    at AbiCoder.encode (abi-coder.js:897)
    at ABICoder.encodeParameters (index.js:96)
    at eval (index.js:432)
    at Array.map (<anonymous>)
```
- [x] Create new question function selector should have correct validation

**Comment by PUndef** [comment]
- [x] Incorrect formula from step 1 cuase error on step 2

Error in concole:
```
Uncaught (in promise) Error: invalid number value (arg="_formula", coderType="uint256", value=null)
    at Object.throwError (errors.js:68)
    at CoderNumber.encode (abi-coder.js:353)
    at eval (abi-coder.js:605)
    at Array.forEach (<anonymous>)
    at pack (abi-coder.js:604)
    at CoderArray.encode (abi-coder.js:704)
    at eval (abi-coder.js:605)
    at Array.forEach (<anonymous>)
    at pack (abi-coder.js:604)
    at CoderTuple.encode (abi-coder.js:764)
```

it is necessary to somehow show the user why the error occurred.
either some special way to validate the formula field.
or a message that makes it clear why an error occurred

**Comment by Stablex** [comment]
- [x] Question may not have a function selector

**Comment by PUndef** [comment]
- [x] incorrect state after close fin pass modal

step for reproduce:
1. Click "**Create question**"
2. Fill data on step 1
3. Fill data on step 2
4. Should open fin pass modal
5. Close modal with fin pass
6. Again click "**Create question**"

get incorrect state:
all field is empty (step 1 & step 2) & current step is 2

**Comment by PUndef** [comment]
> * [x]  Incorrect formula from step 1 cuase error on step 2
> 
> Error in concole:
> 
> ```
> Uncaught (in promise) Error: invalid number value (arg="_formula", coderType="uint256", value=null)
>     at Object.throwError (errors.js:68)
>     at CoderNumber.encode (abi-coder.js:353)
>     at eval (abi-coder.js:605)
>     at Array.forEach (<anonymous>)
>     at pack (abi-coder.js:604)
>     at CoderArray.encode (abi-coder.js:704)
>     at eval (abi-coder.js:605)
>     at Array.forEach (<anonymous>)
>     at pack (abi-coder.js:604)
>     at CoderTuple.encode (abi-coder.js:764)
> ```
> 
> it is necessary to somehow show the user why the error occurred.
> either some special way to validate the formula field.
> or a message that makes it clear why an error occurred

add first version validation in b6a8094b6de64fa8e37b30322988662a863cb9fd

**Comment by PUndef** [comment]
> * [x]  incorrect state after close fin pass modal
> 
> step for reproduce:
> 
> 1. Click "**Create question**"
> 2. Fill data on step 1
> 3. Fill data on step 2
> 4. Should open fin pass modal
> 5. Close modal with fin pass
> 6. Again click "**Create question**"
> 
> get incorrect state:
> all field is empty (step 1 & step 2) & current step is 2

fixed in 64a932966b5b1a1807ef48f1e6ac646e70e8d585

**Comment by PUndef** [comment]
> * [x]  Question may not have a function selector

it's duplicate for first checkbox

**Comment by PUndef** [comment]
@pavkahanov waiting for the correction of the problem on the first flag

**Comment by PUndef** [comment]
- [ ] fix formula validation for use spaces

**Comment by pavkahanov** [comment]
> * Create new question without function selector cause error
>   It's should work correctly without value
>   Error:
> 
> ```
> Uncaught (in promise) Error: invalid bytes4 value (arg="_methodSelector", coderType="bytes4", value="")
>     at Object.throwError (errors.js:68)
>     at CoderFixedBytes.encode (abi-coder.js:433)
>     at eval (abi-coder.js:605)
>     at Array.forEach (<anonymous>)
>     at pack (abi-coder.js:604)
>     at CoderTuple.encode (abi-coder.js:764)
>     at AbiCoder.encode (abi-coder.js:897)
>     at ABICoder.encodeParameters (index.js:96)
>     at eval (index.js:432)
>     at Array.map (<anonymous>)
> ```
fixed in c8de3dabc608e3c80148dff5d58076ebd016f73a

**Comment by PUndef** [comment]
fix formula validation for use spaces

**Comment by PUndef** [comment]
other points are correct

**Comment by PUndef** [comment]
fixed in **fix/122_question_without_selector**
