### ISSUE TITLE
Disable state with active voting

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#124]
Now this state checked only on page component mount.
- [x] On add new question this state is incorrect
- [x] On close voting from other app, this state be incorrect (but state voting correct)
- [ ] Buttons should be disabled for send fin password, if state changed in period before new active vote appeared

**Comment by pavkahanov** [comment]
instead of disabling fin pass form, we disable buttons in modals, which starts new vote and opening fin-pass form

**Comment by PUndef** [comment]
fix this problem https://github.com/Neos1/zeroone/issues/168, & other forms must also be checked
