### ISSUE TITLE
Add some hint or info for understanding

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#125]
The following describes cases where further clarification is required.

- [x] 1. Voting stats list is empty in case ERC20 tokens
![Screenshot_1](https://user-images.githubusercontent.com/25167303/71566299-17026180-2ae9-11ea-927d-20a00f6245ca.png)

**Comment by PUndef** [comment]
- [x] A message stating that you cannot use a function selector that is not in the contract (create new question functionality)

![Screenshot_2](https://user-images.githubusercontent.com/25167303/72579395-8ced3200-390b-11ea-831e-a027ccc7df3c.png)

**Comment by yes1337-ui** [comment]
Case 1 
![image](https://user-images.githubusercontent.com/46047748/72580612-4994c280-390f-11ea-9a56-070ded1781c6.png)

Case 2
![image](https://user-images.githubusercontent.com/46047748/72580493-dbe89680-390e-11ea-9d6a-8cfdbcef13aa.png)

**Comment by PUndef** [comment]
fixed in **fix/125-some_hint_info_for_understanding**
