### ISSUE TITLE
Add application hardcode value setting

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#153]
For this parameter:
- [x] interval for update data on pages (number, sec)
- [x] Min gas price (number, Gwei)
- [x] Max gas price (number, Gwei)

**Comment by PUndef** [comment]
Need a designer opinion and editing in design @Jenya8

**Comment by yes1337-ui** [comment]
@pzyryanov1995 
![image](https://user-images.githubusercontent.com/46047748/72710245-3dbc3100-3b99-11ea-935c-569c1ea2a8f9.png)

**Comment by pzyryanov1995** [comment]
the button as designed by the designer appears only after changing the values
