### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by yes1337-ui** [Neos1/zeroone#167]
![image](https://user-images.githubusercontent.com/46047748/72698280-1142ed80-3b76-11ea-8a37-17d509be97a4.png)

Datepicker:
- [x] colors

- [x] paddings

- [x] strokes

- [x] sizes 

- [x] triangle

- [x] fonts

- [x] no amount of days hover

- [x] round corners

 isn't like in design

Input:

- [x] no input state

- [x] no arrow in input

- [x] no empty space under arrow

**Comment by yes1337-ui** [comment]
Mechanic bugs:

- [x] It closes becouse of page refresh

- [x] If u pick 10 of January and after that pick 1 of January it will pick only 1 January and don't accept the result. 
Should be: date picker accepts it, numbers are changing in input to be shown as from 1 January to 10 January 

- [x] Enchancment: we need a discard button. 
![image](https://user-images.githubusercontent.com/46047748/72698852-8ca59e80-3b78-11ea-8c0b-256108d311a1.png)

- [x] Month should change only in back or right side, Not the whole date area

Mechanics example. Link is in 107 comment
![image](https://user-images.githubusercontent.com/46047748/72699188-fa05ff00-3b79-11ea-89db-d6c084a5b839.png)

**Comment by PUndef** [comment]
fixed in: **fix/167-date_picker** branch
