### ISSUE TITLE
Render problem

### ISSUE THREAD

**Issue by yes1337-ui** [Neos1/zeroone#171]
All icons don't look clean
![image](https://user-images.githubusercontent.com/46047748/72699830-84e7f900-3b7c-11ea-8caf-4d40909c24b9.png)

**Comment by PUndef** [comment]
Create a group of questions hint border render strange
![Screenshot_5](https://user-images.githubusercontent.com/25167303/72702782-78689e00-3b86-11ea-9acb-99266d4909aa.png)

**Comment by yes1337-ui** [comment]
Fonts have that problem too
App
![image](https://user-images.githubusercontent.com/46047748/72713087-f6d13a00-3b9e-11ea-840d-dafe218fbc13.png)
Design
![image](https://user-images.githubusercontent.com/46047748/72713148-17998f80-3b9f-11ea-9a5b-6e7b4759a50c.png)
