### ISSUE TITLE
Votings tab

### ISSUE THREAD

**Issue by yes1337-ui** [Neos1/zeroone#173]
- [x] wrong weight (checked)
![image](https://user-images.githubusercontent.com/46047748/72702444-4a368e80-3b85-11ea-8188-42ca521e9b1d.png)

- [x] add status sorting (checked)
![image](https://user-images.githubusercontent.com/46047748/72702495-7b16c380-3b85-11ea-9715-9b3730b18c35.png)

- [x] add more space between the lines (checked)
![image](https://user-images.githubusercontent.com/46047748/72702547-a6011780-3b85-11ea-8e0d-06849d53d525.png)

- [x] align text as on questions tab and design (checked)

![image](https://user-images.githubusercontent.com/46047748/72702590-d6e14c80-3b85-11ea-93b0-c8eef407ec67.png)

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72703121-57ed1380-3b87-11ea-98fb-6ca4ed26c179.png)

- [x] Wrong button name

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72703866-69cfb600-3b89-11ea-8a81-95c1674d403c.png)

- [x] looks like font is too small or bold

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72704742-317da700-3b8c-11ea-9806-4d95ac8116d9.png)

- [x] too big arrow (checked)

- [x] useless empty space (checked)

- [x] useless scroller (checked)

- [x] add hover on lines (checked)

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72704898-891c1280-3b8c-11ea-9b82-68dcb8031d87.png)

- [x] question icon looks strange

- [x] missing border

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72705156-40188e00-3b8d-11ea-8822-1a5022bd7dfa.png)

- [x] delete that

![image](https://user-images.githubusercontent.com/46047748/72705166-4dce1380-3b8d-11ea-966c-4f975102289f.png)

- [x] add focused state

**Comment by PUndef** [comment]
> ![image](https://user-images.githubusercontent.com/46047748/72705156-40188e00-3b8d-11ea-8822-1a5022bd7dfa.png)
> 
> * [x]  delete that
> 
> ![image](https://user-images.githubusercontent.com/46047748/72705166-4dce1380-3b8d-11ea-966c-4f975102289f.png)
> 
> * [x]  add focused state

focused state not fixed

**Comment by PUndef** [comment]
> ![image](https://user-images.githubusercontent.com/46047748/72704898-891c1280-3b8c-11ea-9b82-68dcb8031d87.png)
> 
> * [x]  question icon looks strange
> * [x]  missing border


**icon not fixed** 
![Screenshot_3](https://user-images.githubusercontent.com/25167303/73149930-3a272d80-40f6-11ea-9cdf-37560888a9bb.png)

**in fullscreen border incorrect**
![Screenshot_4](https://user-images.githubusercontent.com/25167303/73149981-912d0280-40f6-11ea-9141-e06ebb0f365f.png)

**Comment by PUndef** [comment]
> > ![image](https://user-images.githubusercontent.com/46047748/72705156-40188e00-3b8d-11ea-8822-1a5022bd7dfa.png)
> > 
> > * [x]   delete that
> > 
> > ![image](https://user-images.githubusercontent.com/46047748/72705166-4dce1380-3b8d-11ea-966c-4f975102289f.png)
> > 
> > * [x]   add focused state
> 
> focused state not fixed

I don’t see the border changing color
