### ISSUE TITLE
Members tab

### ISSUE THREAD

**Issue by yes1337-ui** [Neos1/zeroone#176]
- [x] Rename to "Начать голосование за назначение администратором группы"![image](https://user-images.githubusercontent.com/46047748/72704136-6e489e80-3b8a-11ea-823a-986b679b738b.png)

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72704326-06df1e80-3b8b-11ea-8dcd-e9224545c483.png)

- [x] Make whole hover area clickable

- [x] Correct alignings

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72704536-9e447180-3b8b-11ea-876a-85fc3a79685b.png)

- [x] Show validation message after click on button, not after input unfocus. **If input is empty**

**Comment by PUndef** [comment]
> ![image](https://user-images.githubusercontent.com/46047748/72704536-9e447180-3b8b-11ea-876a-85fc3a79685b.png)
> 
> * [x]  Show validation message after click on button, not after input unfocus. **If input is empty**

incorrect behavior

**Comment by PUndef** [comment]
> ![image](https://user-images.githubusercontent.com/46047748/72704326-06df1e80-3b8b-11ea-8dcd-e9224545c483.png)
> 
> * [x]  Make whole hover area clickable
> * [x]  Correct alignings

whole hover area clickable is incorrect behavior

**Comment by PUndef** [comment]
fixed in **fix/176-members_tab** branch
