### ISSUE TITLE
Dynamic added question not show by filter

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#179]
1. Create voting for adding new question
2. Voting for adding
3. Complete the voting
4. New question appeared in list question (it's correct)

but this questions have incorrect type for __groupId__ parameter. because of this, when using a filter by type, this question does not appear in the results

**Comment by pzyryanov1995** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/25167303/72707048-1b72e500-3b92-11ea-8ab5-40dc95d84e73.png)

**Comment by PUndef** [comment]
fixed in **fix/179-dynamic_added_question**
