### ISSUE TITLE
New account

### ISSUE THREAD

**Issue by yes1337-ui** [Neos1/zeroone#182]
![image](https://user-images.githubusercontent.com/46047748/72708286-f8960000-3b94-11ea-8a78-998ac85c6f9f.png)

- [x] WHYY?

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72708540-8f62bc80-3b95-11ea-810d-f71a6cce67e1.png)

- [x] ? somewhy isnt a spec symble

- [x] validation visual bug

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72708690-df418380-3b95-11ea-8fa7-58d2717504c9.png)

- [x] icon

- [x] align

- [x] text near form should be bolder

**Comment by PUndef** [comment]
why there are cleared after error in pass confirm field?

![image](https://user-images.githubusercontent.com/25167303/73147081-6176fe00-40e8-11ea-8343-97e8035c7cb0.png)

**Comment by PUndef** [comment]
others problem solved
