### ISSUE TITLE
Footer problem

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#183]
- [x] fix empty space

![image](https://user-images.githubusercontent.com/25167303/72708648-c6d16900-3b95-11ea-8835-8476cfd6cbd7.png)

- [x] footer should be in bottom page not bottom content (16px from bottom). if content bigger than height window, footer should be after content (top 80px)

![Screenshot_3](https://user-images.githubusercontent.com/25167303/72708975-71e22280-3b96-11ea-9eef-01641d2e24db.png)

**Comment by pzyryanov1995** [comment]
![image](https://user-images.githubusercontent.com/25167303/72708648-c6d16900-3b95-11ea-8835-8476cfd6cbd7.png)

**Comment by PUndef** [comment]
fixed in **fix/183-footer_problem**
