### ISSUE TITLE
Empty state

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#189]
- [x] Case for empty filter result on voting page

- [x] Case for empty voting list
![Screenshot_1](https://user-images.githubusercontent.com/25167303/72713609-ee2d3380-3b9f-11ea-9708-3d2099d43df1.png)

- [x] Case for empty filter result on questions page
![image](https://user-images.githubusercontent.com/25167303/72713575-de155400-3b9f-11ea-89dc-3d29c749a5f4.png)

**Comment by pzyryanov1995** [comment]
- [ ] Case for empty filter result
![image](https://user-images.githubusercontent.com/25167303/72713575-de155400-3b9f-11ea-89dc-3d29c749a5f4.png)

- [ ] Case for empty voting list
![Screenshot_1](https://user-images.githubusercontent.com/25167303/72713609-ee2d3380-3b9f-11ea-9708-3d2099d43df1.png)

**Comment by yes1337-ui** [comment]
![image](https://user-images.githubusercontent.com/46047748/72714716-c2ab4880-3ba1-11ea-86ff-ec5d6b54509d.png)

**Comment by PUndef** [comment]
fixed in **fix/189-empty_state**
