### ISSUE TITLE
Remove text after transfer token

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#194]
![Screenshot_1](https://user-images.githubusercontent.com/25167303/72771190-b1f6e300-3c32-11ea-81b0-b41fc6664120.png)

**Comment by PUndef** [comment]
need update design for this dialog @Jenya8

**Comment by pzyryanov1995** [comment]
need to check with the designer. is the current option acceptable

**Comment by PUndef** [comment]
add new issue for design to: https://github.com/Neos1/zeroone/issues/205
