### ISSUE TITLE
Settings and Modal with confirming app reload

### ISSUE THREAD

**Issue by pavkahanov** [Neos1/zeroone#200]

**Comment by PUndef** [comment]
the button as designed by the designer appears only after changing the values

**Comment by PUndef** [comment]
see comment https://github.com/Neos1/zeroone/issues/153#issuecomment-576161926

**Comment by PUndef** [comment]
there are no messages and does not work with such values

![image](https://user-images.githubusercontent.com/25167303/73042140-a6a1f280-3e92-11ea-9e5c-7676d8e85db5.png)
