### ISSUE TITLE
Token transfer incorrect for Custom group

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#206]
I try to transfer money from my wallet as part of a custom group, but I get an error
![Screenshot_2](https://user-images.githubusercontent.com/25167303/73043423-a0624500-3e97-11ea-9dec-39850f02445c.png)
![Screenshot_3](https://user-images.githubusercontent.com/25167303/73043424-a0624500-3e97-11ea-9599-9d3da0a0c177.png)
![Screenshot_4](https://user-images.githubusercontent.com/25167303/73043426-a0fadb80-3e97-11ea-8ea7-1c7ece5f66e0.png)

**Comment by pavkahanov** [comment]
Problem fixed, it cause in old version of Custom Tokens contract
