### ISSUE TITLE
Error state visual bug

### ISSUE THREAD

**Issue by yes1337-ui** [Neos1/zeroone#21]
Стейты налазят
![image](https://user-images.githubusercontent.com/46047748/68739930-94970e80-061c-11ea-8ac6-1b22a0a8e7f9.png)

**Comment by yes1337-ui** [comment]
Не сбрасывается, после повторного фокуса
![image](https://user-images.githubusercontent.com/46047748/68740626-150a3f00-061e-11ea-92f9-3fa97140968f.png)

**Comment by pavkahanov** [comment]
@Jenya8  поля работают таким образом, чтобы стейт исчезал после ввода валидных данных, так работают формы
