### ISSUE TITLE
Do we need an exit button?

### ISSUE THREAD

**Issue by yes1337-ui** [Neos1/zeroone#26]
По ходу нужна. Если перезапуск так и будет значительное время занимать. Да и вообще без этого странно. Думаю будут кейсы, где придется переключаться между кошельками

**Comment by pavkahanov** [comment]
@Jenya8 yep, that button needed

**Comment by pavkahanov** [comment]
Throw to login screen

**Comment by PUndef** [comment]
fixed with this issue https://github.com/Neos1/zeroone/issues/107
