### ISSUE TITLE
Create pass work incorrect

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#29]
Сначала ввёл разные пароли, получил ошибку.
Затем в обоих полях ввёл пароль 123!@#qweQWE (соответствует формату)
Однако приложение почему-то не переходит на следующий шаг

![Screenshot_6](https://user-images.githubusercontent.com/25167303/68750872-33c70080-0633-11ea-9257-39ec24a648e0.png)

**Comment by PUndef** [comment]
С паролем T3sting! почему-то работает. Видать косяк в валидации где-то

**Comment by pavkahanov** [comment]
@pzyryanov1995 У тебя пароль не прошел по списку символов. надо видимо его указать явно

**Comment by pavkahanov** [comment]
fixed
