### ISSUE TITLE
Clear reserve phrase form

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#36]
Не знаю можно ли считать это проблемой. Ситуация такая

Заходим в создание нового ключа.
Переходим на шаг заполнения формы вводим часть данных в поля.
Затем возвращаемся на шаг назад
И затем снова вперёд, те данные которые вводил пользователь больше недоступны, приходится вводить всё заново

**Comment by pavkahanov** [comment]
это нормально, это дает понимание важности и заставляет где-то записать фразу, чтобы не забыть её
