### ISSUE TITLE
Pagination no data state

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#52]
When page no data, pagination state look incorrect

![Screenshot_3](https://user-images.githubusercontent.com/25167303/71052120-082cbe00-217d-11ea-8658-00837654ce31.png)

**Comment by PUndef** [comment]
@Jenya8 need design for this

**Comment by yes1337-ui** [comment]
@pzyryanov1995 what the point of showing empty pagination? If there is no - hide it

**Comment by PUndef** [comment]
fixed in: https://github.com/Neos1/zeroone/tree/bug_fix--52
