### ISSUE TITLE
Field placeholders not changing locale on i18n language change 

### ISSUE THREAD

**Issue by pavkahanov** [Neos1/zeroone#58]
When you trigger language change by lang switcher, placeholders not change their locales

**Comment by PUndef** [comment]
on multiple language change is not work correct

![Screenshot_3](https://user-images.githubusercontent.com/25167303/72582779-81ebcf00-3916-11ea-804d-08511e1df4b5.png)

**Comment by PUndef** [comment]
create new issue with field errors https://github.com/Neos1/zeroone/issues/144
