### ISSUE TITLE
Выбор кошелька, ширина опций больше поля

### ISSUE THREAD

**Issue by PUndef** [Neos1/zeroone#7]
![Screenshot_2](https://user-images.githubusercontent.com/25167303/68469652-27b2fb80-024d-11ea-9020-71e673776e72.png)

**Comment by pavkahanov** [comment]
@pzyryanov1995 так быть и должно, они будут еще длиннее, там будут отображаться балансы
![Снимок экрана от 2019-11-11 14-03-33](https://user-images.githubusercontent.com/45582849/68567656-16a3fd80-048c-11ea-9cb4-9d9c986c8f0d.png)
